server:
  port: 8777
spring:
  application:
    name: test
  #    数据源配置
  datasource:
    url: jdbc:mysql://
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#xml方式必须配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.database.table
