server:
  port: 8777
spring:
  application:
    name: test
  #    数据源配置
  datasource:
    url: jdbc:mysql://wuliu-test-cluster.rwlb.rds.aliyuncs.com:3306/wuliu_test?characterEncoding=UTF-8
    username: yunwei_test
    password: Yunwei_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #  test:
    #    datasource:
    #      url:
    #      username:
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #      type: com.alibaba.druid.pool.DruidDataSource

    #    数据池配置信息
      #       初始化建立的物理连接数
    initial-size: 5
    #           最小连接池数量
    min-idle: 5
    #           最大连接池数量
    max-active: 20
    #           获取连接时最大等待时间
    max-wait: 60000
    #             有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
    #                        2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    time-between-eviction-runs-millis: 60000
    #            连接保持空闲而不被驱逐的最小时间
    min-evictable-idle-time-millis: 300000
    #            用来检测连接是否有效的sql，要求是一个查询语句，常用SELECT 1 FROM DUAL。
    validation-query: SELECT 1 FROM DUAL
    #            建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    #            申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    #            归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    #            是否缓存preparedStatement
    pool-prepared-statements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: 20
#    #    配置监控统计拦截的filters 去掉后监控界面sql无法统计，‘wall’用于防火墙
#    filters: stat,wall,log4j
#    # 合并多个DruidDataSource的监控数据
#    use-global-data-source-stat: true
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connect-properties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500


#xml方式必须配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.database.table
